//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJpegCameraProxy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MJpegCameraProxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] animated_overlay {
            get {
                object obj = ResourceManager.GetObject("animated_overlay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery UI - v1.10.2 - 2013-03-14
        ///* http://jqueryui.com
        ///* Includes: jquery.ui.core.css, jquery.ui.accordion.css, jquery.ui.autocomplete.css, jquery.ui.button.css, jquery.ui.datepicker.css, jquery.ui.dialog.css, jquery.ui.menu.css, jquery.ui.progressbar.css, jquery.ui.resizable.css, jquery.ui.selectable.css, jquery.ui.slider.css, jquery.ui.spinner.css, jquery.ui.tabs.css, jquery.ui.tooltip.css
        ///* To view and modify this theme, visit http://jqueryui.com/themeroller/
        ///* Copyright 2013 jQuery Foundation and ot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_1_10_2_custom_min_css {
            get {
                return ResourceManager.GetString("jquery_ui_1_10_2_custom_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery UI - v1.10.2 - 2013-03-14
        ///* http://jqueryui.com
        ///* Includes: jquery.ui.core.js, jquery.ui.widget.js, jquery.ui.mouse.js, jquery.ui.position.js, jquery.ui.accordion.js, jquery.ui.autocomplete.js, jquery.ui.button.js, jquery.ui.datepicker.js, jquery.ui.dialog.js, jquery.ui.draggable.js, jquery.ui.droppable.js, jquery.ui.effect.js, jquery.ui.effect-blind.js, jquery.ui.effect-bounce.js, jquery.ui.effect-clip.js, jquery.ui.effect-drop.js, jquery.ui.effect-explode.js, jquery.ui.effect-fade.js, jquery.ui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_1_10_2_custom_min_js {
            get {
                return ResourceManager.GetString("jquery_ui_1_10_2_custom_min_js", resourceCulture);
            }
        }
        
        internal static byte[] ui_bg_flat_0_aaaaaa_40x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_0_aaaaaa_40x100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_bg_flat_75_ffffff_40x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_75_ffffff_40x100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_bg_glass_55_fbf9ee_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_55_fbf9ee_1x400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_bg_glass_65_ffffff_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_65_ffffff_1x400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_bg_glass_75_dadada_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_75_dadada_1x400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_bg_glass_75_e6e6e6_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_75_e6e6e6_1x400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_bg_glass_95_fef1ec_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_95_fef1ec_1x400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_bg_highlight_soft_75_cccccc_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_75_cccccc_1x100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_icons_222222_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_222222_256x240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_icons_2e83ff_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_2e83ff_256x240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_icons_454545_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_454545_256x240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_icons_888888_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_888888_256x240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ui_icons_cd0a0a_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_cd0a0a_256x240", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
